meas_std_val: 0.03
u_std: [0.04, 0.04, 0.04, 0.04]
initial_range: [1.0, 1.0, 1.0, 0.25, 0.25, 0.25]
num_particles: 100
stale_filter_time: 1.0

max_objects:
  power_cell: 2

labels:
- BACKGROUND
- power_cell
