default_duration_limit: 150  # Maximum time difference between newest and oldest message, seconds, overrides -d flag
topics:
- /tj2/odom

- /front_laser/scan
- /rear_laser/scan
# TODO: include merged laser scan topic

- /camera/color/image_raw
- /camera/depth/image_raw
# TODO: fill out the rest of the camera topics

- /tj2/ping
- /tj2/robot_status
- /tj2/cmd_vel

- /tf

# TODO: game object detection
