joystick:
  package: "tj2_debug_joystick"
  path: "tj2_debug_joystick.launch"
  topics:
    /joy: None
  on_start: true
move_base:
  package: "tj2_move_base"
  path: "tj2_move_base.launch"
  on_start: false
  topics:
    /move_base: None
move_base_flex:
  package: "tj2_move_base"
  path: "tj2_move_base_flex.launch"
  on_start: false
rplidar:
  package: "tj2_rplidar"
  path: "tj2_rplidar.launch"
  on_start: true
  topics:
    /laser/scan_filtered: 2.0
limelight:
  package: "tj2_limelight"
  path: "tj2_limelight.launch"
  on_start: false
gameobjects:
  package: "tj2_gameobjects"
  path: "tj2_gameobjects.launch"
  on_start: false
yolo:
  package: "tj2_yolo"
  path: "tj2_yolo.launch"
  on_start: true
